In [10]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [11]:
data = pd.read_excel('beta.xlsx')
data

           일자   종목 A     시장지수  종목 초과수익률  시장지수 초과수익률
0  2023-04-28  13240  2501.53       NaN         NaN
1  2023-05-02  14030  2524.39      0.06        0.01
2  2023-05-03  13500  2501.40     -0.04       -0.01
3  2023-05-04  13190  2500.94     -0.02        0.00
4  2023-05-08  12820  2513.21     -0.03        0.00
..        ...    ...      ...       ...         ...
63 2023-08-01  34950  2667.07      0.01        0.01
64 2023-08-02  33050  2616.47     -0.06       -0.02
65 2023-08-03  34000  2605.39      0.03        0.00
66 2023-08-04  33300  2602.80     -0.02        0.00
67 2023-08-07  29850  2580.71     -0.12       -0.01

[68 rows x 5 columns]

In [12]:
data['일자'] = pd.to_datetime(data['일자'])
data.set_index('일자', inplace=True)
data = data.dropna()

In [14]:
#선형 회귀
X = sm.add_constant(data['시장지수 초과수익률'])  
y = data['종목 초과수익률']  

#선형 회귀 모델 : sm.OLS
#fit() : 회귀모델 적합 시키는 것 
model = sm.OLS(y, X).fit()
beta = model.params['시장지수 초과수익률']
print(f"Beta: {beta}")

Beta: 3.550533807829183